[Database]
Host = '$SURREAL_DB_ADDRESS'
Port = $SURREAL_DB_PORT
User = '$SURREAL_DB_USER'
Password = '$SURREAL_DB_PASSWORD'

[S3Bucket]
Endpoint = '$MINIO_ADDRESS:$MINIO_PORT'
AccessKey = '$MINIO_ACCESS_KEY'
Secret = '$MINIO_SECRECT_KEY'
SSL = false

[Server]
FrontendProtocol = "http"
FrontendHost = "localhost"
FrontendPort = 5173
Port = 8080
AdminPasswordHash = '$MANIFOLD_ADMIN_PASSWORD_HASH'
