package types

//go:generate stringer -type=ErrorCode
type ErrorCode int

const (
	FAILED_TO_GENERATE_SCHEMA ErrorCode = iota + 100
	USER_ALREADY_EXISTS
	USER_NOT_FOUND
	WRONG_PASSWORD
	REGISTRATION_KEY_NOT_FOUND
	REGISTRATION_KEY_WRONG
	USER_ALREADY_VERIFIED
	FAILED_TO_GENERATE_SESSION_TOKEN
	FAILED_TO_SAVE_SESSION_TO_DATABASE
	FAILED_TO_AUTHENTICATE_USER
	FAILED_TO_FETCH_USER
	FAILED_TO_UNMARSHAL_USER
	FAILED_TO_UNMARSHAL_SESSION
	GRAPH_NODE_NOT_FOUND
	GRAPH_HANDLE_NOT_FOUND
	INCOMPATIBLE_HANDLE_IO_TYPES
	MISSING_NODE_DATA
	TRIED_TO_EXECUTE_BASENODE
)
